### ISSUE TITLE
Utilização dos arquivos LAZ

### ISSUE THREAD

**Issue by ickbravo** [geoinfo-smdu/geosampa-mais-livre#11]
Boa tarde, pessoal! Então. Primeiramente parabéns pelo trabalho no Geosampa.
Acada dia que passa eu fico mais maravilhado com o site!

Eu, infelizmente, não se minha dúvida poderá ser sanada, pois não sei se ela diz respeito ao geosampa.

Sou cinegrafista e diretor, e recentemente com a impossibilidade de sair de casa decidi trabalhar um projeto pessoal. E eu decidi que queria fazer um vídeo usando Point cloud. 
Eis que pra minha surpresa eu descubro da existencia do Geo sampa e tudo que eu tinha em mente pode ser concretizado - já que nao possuo o equipamento necessário pra fazer a captura eu mesmo-.

Enfim, ao baixar os arquivos eu notei que a maioria dos programas não trabalham com o LAZ.
Todavia a principio eu converti os arquivos em PTS e consegui trabalhar com eles dentro da Unreal Engine. 
Segue aqui um resultado bem em baixa do que tenho feito: https://youtu.be/0NSH2cLkit0
E aqui uma video da tela:  https://www.youtube.com/watch?v=K3EY6NLhV7o&feature=youtu.be

Porém eu descobri uma forma de usar Point Cloud dentro da Unity (convertendo-os em PLY) que me permite "desmembrar" o Point Cloud e extrair do mesmo uma imagem com um Position Map. (Isso me permitiria tratar o PointCloud como uma textura 3D. Assim eu posso ter um numero de pontos muito maior e animá-los. Obtendo um resultado semelhante a esse: https://www.youtube.com/watch?v=EuAqCf63VXE

Se tiverem interesse, segue o projeto que torna isso possível: https://github.com/keijiro/Pcx/tree/vfxgraph-example

Eu basicamente consegui trabalhar na Unity e com esses efeitos visuais com todos os arquivos Point Clouds que eu achei na internet! Menos com os que eu baixei do Geosampa.

Voces sabem me dizer se existe um porque? Já que eu consigo perfeitamente usar os arquivos (com cor) na Unreal Engine (e em outros programas de leitura/edição como o Metashape)

E mais uma vez, eu imagino que talvez vocês não consigam me ajudar nisso, mas eu não tenho a quem mais perguntar!!!!
Então muito obrigado, e parabéns pelo Geosampa!

**Comment by yubathom** [comment]
@feromes, veja se consegue dar uma luz para o @ickbravo.. ele me procurou e pedi para criar uma issue. Lembrei que estava trabalhando em um visualozador de LAZ e imaginei que talvez pudesse ajudá-lo de alguma forma.

**Comment by yubathom** [comment]
relacionado a #3

**Comment by feromes** [comment]
Sensacional saber disso @ickbravo 

Nuvens de pontos vindas de levantamentos LiDAR costumam vir em formato LAZ. Mas é possível converter em PLY e na maioria dos formados. Temos um pouco mais de 33 bilhões de pontos a sua disposição. Me conta mais um pouco do que vc precisa na prática que ajudo vc a montar um conversor.

Estamos acostumados a usar Python com a bilioteca PDAL para fazer isso.

A nuvem de pontos tem diversas peculiaridades, devemos soltar um artigo em breve para cobrir diversos assuntos. 

Um aplicativo bacana para vc usar e converter é o CloudCompare, vc já instalou?

Vou acompanhar mais esses Issues aqui, acabei demorando um pouco para responder, mas pode contactar!

Abcs,

Fernando Gomes

**Comment by ickbravo** [comment]
Meu caro, @feromes ! Já fico muito feliz só por tentar me ajudar! Já significa muito, dado ao quão perdido eu estou! hahahah!!

Acabei de baixar o CloudCompare aqui e tive o mesmo retorno na conversão. Infelizmente não deu!
Eu entendo muito pouco de programação então vou te passar meu olhar leigo do que aconteceu! hahaha

Esse moço, [Keijiro](https://github.com/keijiro/Pcx/tree/vfxgraph-example) criou um algorito pra Unity que divide os arquivos Point Cloud (PLY) em duas imagens! Uma sendo as cores presentes nos pontos, e uma outra que consegue mapear a posição dos pontos.

O que eu acho que está acontecendo é que existem pontos de mais nos arquivos que eu baixei do GeoSampa (mesmo usando só um bloco). O que na verdade é incrivel né! hahahahah

Upei uma imagem [aqui](https://imgur.com/a/2ZZ318e) pra voce ver. O arquivo que eu baixei em LAZ e converti e PLY vem com uma posição em branca!

Pra voce ter ideia, [esse ](https://imgur.com/a/NDmr01G)é um arquivo de cor de SP, da ate pra notar que só tem predio e arvore (é da paulista).
E [esse ](https://imgur.com/a/hMp4cOL)é um Position map qualquer de um outro PointCloud. É uma loucura

Então eu nem sei muito bem se você pode me ajudar, é um tiro no escuro!
Mas como você entende disso bilhões de vezes mais do que eu, eu estou crente numa possível solução

**Comment by feromes** [comment]
@ickbravo é super importante dar a maior possibilidade possível de uso para os dados que publicamos. Entre outras tantos aspectos isso é democratizar o acesso a informação. 

Em relação a nuvem de pontos acreditamos que a produção de conteudo cultural é um viés muito interessante dessa publicação, como por exemplo o desenvolvimento de visitas e passeios virtuais pela cidade, tanta para entreterimento quanto para a pesqusia aplicada a paisagem urbana. 

Nesse contexto, gostaria de coloborar conosco com um repositório que estimularia os primeiros passos no sentido de importar a nuvem de pontos para Unity e outras engines de game?

A intenção seria criar pequenos trechos de código para dar autonomia ao desenvolvedor poder importar porçoes dos dados LiDAR, seu caso poderia ser o primeiro: Importanto a Nuvem de Pontos para UNITY3D, que tal?

Da nossa parte desenvolveríamos um passo-a-passo para a conversão dos dados para PLY Litle Endian e vc postaria a sua contribuição com um vídeo e imagens da parte do Unity. Que tal?

Abcs,

**Comment by feromes** [comment]
Vou copiar aqui o @DanMizuta que é do GeoInfo, além de um entusiasta e o primeiro que teve a ideia da utilização do LiDAR para produção de conteúdo cultural

**Comment by ickbravo** [comment]
@feromes Com toda certeza, meu caro!
Fico muito feliz com o convite! Pode sim contar comigo com essa parte!
Nos últimos anos duas áreas que tem crescido muito  é o [Virtual filmmaking](https://www.youtube.com/watch?v=gUnxzVOs3rk&t) (que basicamente é fazer um filme inteiro dentro do estúdio, porém sem "pós", e o [Volumentric Filmmaking](https://www.youtube.com/watch?v=i4Al7iVvIkI) (que tenta criar um mundo e/ou personagens em full 3D pra poder ter o máximo de liberdade de criação).

Eu acredito que o PC vai ser fundamental nessas duas áreas, então venho estudado bastante!
Isso sem contar nas possibilidades quanto a informação, didática, recreamento!
Então vai ser uma honra poder fazer parte disso (mesmo que pouquinho hahaha).


E assim, lembrando que na Unreal Engine, que é bem usada pra visualização arquitetônica, os arquivos já funcionam perfeitamente! E já é possível fazer bastante coisa!
Fiz [aqui ](https://www.youtube.com/watch?v=sgwcTvcIP-M&feature=youtu.be)um leve passeio um pouco menos "experimental", só pra voces verem! hehehhe

Abraços!!

**Comment by feromes** [comment]
@ickbravo acabei de criar um repositório (https://github.com/geoinfo-smdu/lidar3d-game-engines) para ajudar a quem quiser gerar conteudo cultural a partir de nuvem de pontos como é seu caso e queria te pedir para testar lá nossa primeira tentativa. Vou fechar esse issue aqui e já abri um outro lá, ok?

https://github.com/geoinfo-smdu/lidar3d-game-engines/issues/1
